---
title: "rain caos"
date: '`r format(Sys.Date(), "%b %d, %Y")`'
output:
  html_document:
    toc: true
    theme: cosmo
  word_document: default
  pdf_document: default
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
```


Loading packages
```{r packages, include=FALSE}
library(ggplot2)
library(tidyverse)
library(jcolors)
library(ggfortify)
library(lubridate)
library(zoo)
```

```{r}
new_Date<-new_daterain#rain data each 10 min
class(new_Date$dates)
new_Date$dates<- as.character(new_Date$dates)
new_Date$aproxh.x<- new_Date$dates
rain.wide <- pivot_wider(new_Date, names_from = site_id_en, values_from = acc_Rain)

#now calculate previous 12 hours
rain.wide$sumsGoya12 <- rollsumr(rain.wide$Goya, k = 144, fill = NA)
rain.wide$sumsKuniga12 <- rollsumr(rain.wide$Kuniga, k = 144, fill = NA)
rain.wide$sumsYomitan12<- rollsumr(rain.wide$Yomitan, k = 144, fill = NA)

#select each of the places in different df
#Goyarain<- new_daterain %>% filter(grepl('Goya', site_id_en))
#Kuniyarain<- new_daterain %>% filter(grepl('Kuniya', site_id_en))
#Yomitanrain<- new_daterain %>% filter(grepl('Yomitan', site_id_en))

#on the other hand we have mean that includes rinkodata values.
rinkotimes
class(rinkotimes$totaltime)
aproh<- as.character(rinkotimes$totaltime)
aproxh<- ymd_hms(aproh)
aproxh<- floor_date(aproxh, unit = "hour")
aproxh<- as.character(aproxh)
joinaprox<- cbind(rinkotimes, aproxh)
joinaprox<- joinaprox[ , -c(1, 2, 4)]

# Compute the mean of multiple columns
df2 <- joinaprox %>% group_by(aproxh, sample) %>% 
  summarise(sal=mean(salinity),
            temp= mean(water_temp),
            .groups = 'drop', na.rm = TRUE) %>%
  as.data.frame()

# Compute the mean of multiple columns
df2 <- joinaprox %>% group_by(aproxh, sample) %>% 
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>%
  as.data.frame()

df2$sample<- gsub('Ｒ１Ｃ', 'R1C',
           gsub('Ｒ１Ｎ', 'R1N',
           gsub('Ｒ１Ｓ', 'R1S', 
           gsub('Ｒ２Ｃ', 'R2C', 
           gsub('Ｒ２Ｎ', 'R2N', 
           gsub('Ｒ２Ｓ', 'R2S',       
           gsub('Ｕ１Ｃ', 'U1C', 
           gsub('Ｕ１Ｎ', 'U1N',
           gsub('Ｕ１Ｓ', 'U1S',
           gsub('Ｕ２Ｃ', 'U2C',
           gsub('Ｕ２Ｎ', 'U2N',
           gsub('Ｕ２Ｓ', 'U2S', df2$sample))))))))))))

df2$dates<- df2$aproxh
df2$dates<-gsub(" .*","", df2$dates)

#tides
tide <- read.csv("~/Documents/GitHub/DNA_monitOki/Rain, wind, tides/jma_hourly_tidelevel.csv")
trial<- tide
tri<- trial %>%
  mutate(across('Date.time', str_replace, '/', '-'),
  mutate(across('Date.time', str_replace, '/', '-')))
tri$Date.time<-parse_date_time(tri$Date.time, "ymd HM")
tri$aproxh<- as.character(tri$Date.time)
head(tri)
tri$Date.time<- tri$aproxh

#nutrient data does not have the time. Therefore makes more challenging the full join. We take the df "nutrientdata" from the Rain_wind Rmarkdown which contains same data but only for dates (not times included). This df also includes average wind data

head(nutrientdata)


#first we need to clean the table
newnutrient<- nutrientdata[, -grep("_SD", colnames(nutrientdata))]
data.frame(colnames(newnutrient)) #to know the number of columns
newnutrients<- newnutrient[ , -c(17:19)]
newnutrients$dates<- newnutrient$date.x
newnutrients$dates<- as.character(newnutrients$dates)

```

Lets put all together
```{r}
by=c('team'='team_name', 'pos'='position')
Full<- df2 %>%
  full_join(newnutrients, by=c("dates","sample"="sample.x"), keep = TRUE) %>%
  full_join(tri, by ="aproxh", keep = TRUE) %>%
  full_join(rain.wide, by ="aproxh.x", keep = TRUE)
names(Full)[1] <- "date_time"
#clean from extra columns
newfull<- Full[ , -c(3, 7, 9, 10, 14, 15, 16, 17, 20, 21:36, 39, 40, 41, 47, 48, 49, 51, 52, 53, 54, 55, 56)]

#reorder and rename columns
names(newfull)[1] <- "date_time"
names(newfull)[19] <- "tide"
names(newfull)[12] <- "wind_Nago"
names(newfull)[13] <- "wind_Naha"
colnames(newfull)<-gsub("_Mean","",colnames(newfull))


#cleanfull <- newfull[, c(1, 17, 2, 18, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32)]
#this contains all the data to be correlated. 
#remove the non numeric columns

numeric<- newfull[ , -c(1, 2, 10, 11)]

```

```{r, correlation}
numeric<- numeric[complete.cases(numeric), ]#keep only rows with data in all the cases
res <- cor(numeric) #get the cor matrix
corrplot(res, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45) # correlation plot

```

There is not much correlation between rain and different physicochemical parameters.

```{r, better rain, wind aprox}

U1rain<- Full %>% 
 filter(!grepl("U1",sample))
U1rain<- U1rain[ , c(1, 2, 19, 57)]
names(U1rain)[4] <- "Rain_Acc12h"

U2rain<- Full %>% 
  filter(location == "U2")
U2rain<-U2rain[ , c(1, 2, 19, 58)]
names(U2rain)[4] <- "Rain_Acc12h"

R1rain<- Full %>% 
  filter(location == "R1")
R1rain<- R1rain[ , c(1, 2, 19, 59)]
names(R1rain)[4] <- "Rain_Acc12h"

R2rain<- Full %>% 
  filter(location == "R2")
R2rain<- R2rain[ , c(1, 2, 19, 58)]
names(R2rain)[4] <- "Rain_Acc12h"

totalrain<- rbind(U1rain, U2rain, R1rain, R2rain)
totalrain<- totalrain[complete.cases(totalrain), ]

#now wind
U1wind<- Full %>% 
 filter(!grepl("U1",sample))
U1wind<- U1wind[ , c(1, 2, 19, 38)]
names(U1wind)[4] <- "Wind"

U2wind<- Full %>% 
  filter(location == "U2")
U2wind<-U2wind[ , c(1, 2, 19, 37)]
names(U2wind)[4] <- "Wind"

R1wind<- Full %>% 
  filter(location == "R1")
R1wind<-R1wind[ , c(1, 2, 19, 37)]
names(R1wind)[4] <- "Wind"

R2wind<- Full %>% 
  filter(location == "R2")
R2wind<- R2wind[ , c(1, 2, 19, 37)]
names(R2wind)[4] <- "Wind"

totalwind<- rbind(U1wind, U2wind, R1wind, R2wind)
totalwind<- totalwind[complete.cases(totalwind), ]

#Ahora se une al resto de los datos

rain_wind<- newfull %>%
  full_join(totalrain, by=c("date_time","sample")) %>%
  full_join(totalwind, by=c("date_time","sample"))

rain_wind<- rain_wind[complete.cases(rain_wind), ]
numeric_accurate<- rain_wind[ , -c(1, 2, 10, 11, 12, 13, 20, 21, 22, 23, 25)]
res <- cor(numeric_accurate) #get the cor matrix
corrplot(res, type = "upper", order = "hclust", tl.col = "black", tl.srt = 45) # correlation plot
```

